language: node_js

node_js:
  - 11
  - 12
  - 13            
  - lts/*

before_install:
  - npm install -g codecov
  - npm run docker-build && npm run docker-run

script:
  - npm test
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
