language: node_js

node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13            
  - lts/*

before_install:
  - npm install -g codecov

script:
  - npm test
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
