name: Publish

on:
    release:
        types:
            - created

jobs:
    mockserver-test:
        name: Unit Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodejs: [11, 12, 13, 14, 16, 17, 18, 19]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.nodejs }}
            - name: install dependencies
              run: yarn install
            - name: build and run mockserver docker
              run: yarn run docker-build && yarn run docker-run
            - name: run tests
              run: yarn test

    publish:
        needs:
            - mockserver-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: set version envvar
              run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
            - name: set release version on package.json
              run: sed -i.bak 's/0\.0\.0/'$RELEASE_VERSION'/g' package.json
            - name: check package
              run: cat package.json
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: install dependencies
              run: yarn install
            - name: run build
              run: yarn build
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
