name: Publish

on:
    release:
        types:
            - created

jobs:
    mockserver-test:
        name: Unit Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodejs: [14, 16, 18, 19]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.nodejs }}
            - name: install dependencies
              run: yarn install
            - name: build and run mockserver docker
              run: yarn run docker-build && yarn run docker-run
            - name: run tests
              run: yarn test

    publish-to-npm:
        needs:
            - mockserver-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: set version envvar
              run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
            - name: set release version on package.json
              run: sed -i.bak 's/0\.0\.0/'$RELEASE_VERSION'/g' package.json
            - name: check package
              run: cat package.json
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: install dependencies
              run: yarn install
            - name: run build
              run: yarn build
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}

    publish-to-docker:
        needs:
            - mockserver-test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: set version envvar
              run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: install dependencies
              run: yarn install
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: build image
              run: docker build -t gguridi/mockserver:version-$RELEASE_VERSION .
            - name: push image
              run: docker push gguridi/mockserver:version-$RELEASE_VERSION
